# Generated by Django 5.0.1 on 2024-07-09 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetModel',
            new_name='MyPetModel',
        ),
    ]
