# Generated by Django 5.0.1 on 2024-07-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_rename_petmodel_mypetmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPetModel',
        ),
    ]
