# Generated by Django 5.0.1 on 2024-07-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petapp', '0003_delete_mypetmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
    ]
