# Generated by Django 5.0.1 on 2024-07-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0005_mypetmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypetmodel',
            name='image',
            field=models.ImageField(default='/static/images/fluffy_dog.webp', upload_to='media/'),
        ),
    ]
