# Generated by Django 5.0.1 on 2024-07-13 15:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0003_alter_dairyentry_dairy_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dairyentry',
            name='dairy_id',
        ),
        migrations.AddField(
            model_name='dairyentry',
            name='uid',
            field=models.ForeignKey(db_column='uid', default=datetime.datetime(2024, 7, 13, 15, 22, 31, 618606, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
