# Generated by Django 5.0.1 on 2024-07-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0004_remove_dairyentry_dairy_id_dairyentry_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dairyentry',
            name='created_at',
        ),
    ]
